### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by Bagu** [palinkas-jo-reggelt/hMailServer_CatchSpam#5]
Hello,

I just see an error : 
```
"ERROR"	3872	"2021-10-22 10:20:05.582"	"Severity: 2 (High), Code: HM5032, Source: DALConnection::Execute, Description: MySQL: Data too long for column 'domain' at row 1 (Additional info: INSERT INTO hm_catchspam (domain,hits) VALUES ('li238-145.members.linode.com',1) ON DUPLICATE KEY UPDATE hits=(hits+1),timestamp=NOW();)"
"ERROR"	3872	"2021-10-22 10:20:05.586"	"Script Error: Source: hMailServer COM library - Error: 800403E9 - Description: Execution of SQL statement failed. Error: MySQL: Data too long for column 'domain' at row 1 (Additional info: INSERT INTO hm_catchspam (domain,hits) VALUES ('li238-145.members.linode.com',1) ON DUPLICATE KEY UPDATE hits=(hits+1),timestamp=NOW();) - Line: 86 Column: 1 - Code: (null)"
```
Don't know why and how to avoid it.

**Comment by palinkas-jo-reggelt** [comment]
If you set up the database per the instructions, column domain is 25 char.
`domain varchar(25) NOT NULL,`

However, `li238-145.members.linode.com` is 28 char. 

But the real problem is that the domain should be shortened to its highest level: maindomain.tld, not subdomain(+).maindomain.tld; i.e. linode.com should be the domain inserted into the db. This means that Function GetMainDomain is not being used for some reason. That function shortens the HELO/PTR to maindomain.tld.

The update query gets executed in Function CatchSpam, which is called from Sub OnAcceptMessage. So look at your code in Sub OnAcceptMessage to make sure that it includes `spamDomain = GetMainDomain(PTR_Record)`

Since there is a domain entry in your error log, its clear that you're able to get the PTR, so it must be that its not getting shortened.

The purpose of shortening the domain to its highest level is because what I've found is that spam is coming in on a single maindomain.tld, but while using multiple subdomains. All of them have valid PTRs, etc and get through my other spam filters. Example from my logs:
`nonappealability.com : 74.117.238.114`
`widely.nonappealability.com : 74.117.238.115`
`agree.nonappealability.com : 74.117.238.118`

There are probably more that got blocked. But I know from just looking that if the domain is weird looking (usually 2 words mashed together that don't make sense), then its probably a spammer. Any server on a subdomain of those weird domains is also a spammer. They're all the same to you and me, but not to hmailserver (different names, different IPs, etc). So shortening all of them to their main domain of `nonappealability.com` will block all of them.

Your example domain probably does NOT fall into this category because it looks like its part of a bot net. It may be sending spam, but its not the target of this script. Blacklist check confirms this (https://multirbl.valli.org/lookup/li238-145.members.linode.com.html). Its not on any important blacklists, although its not on any important whitelists either.

This script is only for blocking bona fide spam and should not be used for low scores due to its impact on false positives. In Sub OnAcceptMessage, you must declare your spam delete threshold and only messages that are clearly greater than that should be processed in this script.

```typescript
REM - If SAScore greater than DELETE THRESHOLD - use hMailServer delete threshold score
REM - CatchSpam should only be applied to messages that should be deleted : its used to reject the client outright
If (CInt(SAScore) > 6) Then 
```

**Comment by Bagu** [comment]
So there must be a problem because i have : 
```
	Dim spamDomain, SAScore
	If IsWhitelisted = 0 Then
		If oMessage.HeaderValue("X-hMailServer-Reason-Score") <> "" Then 
			strRegEx = "[0-9]{1,3}"
			Set Matches = oLookup(strRegEx, oMessage.HeaderValue("X-hMailServer-Reason-Score"), False)
			For Each Match In Matches
				SAScore = Match.Value
			Next

			' - If SAScore greater than DELETE THRESHOLD - use hMailServer delete threshold score
			' - CatchSpam should only be applied to messages that should be deleted : its used to reject the client outright
			If (CInt(SAScore) > 6) Then 
				spamDomain = GetMainDomain(PTR_Record)
				EventLog.Write( "Spam Received: Score = " & CInt(SAScore) & ", PTR = " & PTR_Record & " Domain = " & spamDomain )
				If spamDomain <> "" Then 
					Call CatchSpam(spamDomain)
					'
					' Anything else you want to do
					'
				End If
			End If
		End If
	End If
```

And : 
```
Function GetMainDomain(strDomain)
	Dim strRegEx, Match, Matches
	Dim TestDomain, DomainParts, a, i, PubSuffMatch
	Include("d:\hMailServer\Events\public_suffix_list.vbs")
	
	DomainParts = Split(strDomain,".")
	a = UBound(DomainParts)
	If a > 1 Then
		TestDomain = DomainParts(1)
		For i = 2 to a
			TestDomain = TestDomain & "." & DomainParts(i)
		Next
	ElseIf a = 1 Then
		TestDomain = DomainParts(1)
	Else
		Exit Function
	End If

	Set Matches = oLookup(PubSufRegEx, TestDomain, False)
	For Each Match In Matches
		PubSuffMatch = True
	Next

	If PubSuffMatch Then 
		GetMainDomain = DomainParts(0) & "." & TestDomain
	Else
		GetMainDomain = GetMainDomain(TestDomain)
	End If
End Function
```

And d:\hMailServer\Events\public_suffix_list.vbs is the correct path and exist.
I don't know why the domain name is not split to catch the top level domain.

**Comment by palinkas-jo-reggelt** [comment]
I just set up a test script to test GetMainDomain using the following PTRs:

`out-19.smtp.github.com` > Result = `github.com`
`li238-145.members.linode.com` > Result = `li238-145.members.linode.com`

Something strange is going on. I have little league now, so I'll look at this later.

**Comment by palinkas-jo-reggelt** [comment]
The answer is that `members.linode.com` is a tld entry in the public suffix list.

The solution is to alter the database to make `domain` larger:

```typescript
ALTER TABLE `hm_catchspam` CHANGE `domain` `domain` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
```

Or you can just ignore the error since members.linode.com is not a target of the script.

**Comment by palinkas-jo-reggelt** [comment]
On second thought, don't ignore. If the script is picking up on `li238-145.members.linode.com` then that means its sending bona fide spam. If you receive 3 delete-able messages from that server, its safe to say that its only purpose is to generate spam, and can be safely rejected. But LOOK at the messages to be sure!

**Comment by Bagu** [comment]
After a look, the message IS a spam.
I have made the modification on the database. The entry is ok now.

> 
> 
> I just set up a test script to test GetMainDomain using the following PTRs:
> 
> `out-19.smtp.github.com` > Result = `github.com` `li238-145.members.linode.com` > Result = `li238-145.members.linode.com`
> 
> Something strange is going on. I have little league now, so I'll look at this later.

Yes, i don't undestand too.

**Comment by palinkas-jo-reggelt** [comment]
> Yes, i don't undestand too.

Like i said above, members.linode.com is a tld, like .com or .org, just longer. Therefore the full domain `li238-145.members.linode.com` contained NO subdomains. It was the main domain already. Function GetMainDomain properly parsed the domain and gave the correct result. 

```typescript
(maindomain) . (topleveldomain)
    (github) . (com)
 (li238-145) . (members.linode.com)
```
